CREATE DATABASE BUDGETWISE;

USE BUDGETWISE;


CREATE TABLE IF NOT EXISTS TIPO_USUARIO (
    T_TUSUARIO_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    T_TUSUARIO BOOLEAN
);

CREATE TABLE IF NOT EXISTS TIPO_ART (
    T_TART_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    T_TART BOOLEAN
);

CREATE TABLE IF NOT EXISTS TIPO_DNI (
    T_TDNI_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    T_TDNI VARCHAR(10)
);

CREATE TABLE IF NOT EXISTS UBICACION (
    T_UBI_ID INT AUTO_INCREMENT PRIMARY KEY,
    T_UBI_PROVINCIA VARCHAR(50),
    T_UBI_CIUDAD VARCHAR(50),
    T_UBI_FECHA_CREA DATE,
    T_UBI_FECHA_MOD DATE
);

CREATE TABLE IF NOT EXISTS USUARIO (
    T_USU_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    T_USU_NOMBRE VARCHAR(50) NOT NULL,
    T_USU_APELLIDO VARCHAR(50) NOT NULL,
    T_USU_ESTADO BOOLEAN,
    T_TUSUARIO_ID INT NOT NULL,
    T_TDNI_ID INT,
    T_USU_TELEFONO VARCHAR(20) NOT NULL,
    T_UBI_ID INT,
    T_USU_CALLE VARCHAR(50),
    T_USU_NUMCALLE INT,
    T_USU_CP INT,
    T_USU_MAIL VARCHAR(50) NOT NULL,
    T_USU_PASSWORD VARCHAR(50) NOT NULL,
    T_USU_WEB VARCHAR(50),
    T_USU_LOGO VARCHAR(100),
    T_USU_FIRMA VARCHAR(100),
    T_USU_FECHA_CREA DATE,
    T_USU_FECHA_MOD DATE,
    CONSTRAINT FK_USU_TUSU FOREIGN KEY (T_TUSUARIO_ID) REFERENCES TIPO_USUARIO (T_TUSUARIO_ID),
    CONSTRAINT FK_USU_UBI FOREIGN KEY (T_UBI_ID) REFERENCES UBICACION (T_UBI_ID),
    CONSTRAINT FK_USU_TDNI FOREIGN KEY (T_TDNI_ID) REFERENCES TIPO_DNI (T_TDNI_ID)
);

CREATE TABLE IF NOT EXISTS ART (
    T_ART_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    T_TART_ID INT NOT NULL,
    T_ART_NOMBRE VARCHAR(50) NOT NULL,
    T_ART_DESCRIPCION VARCHAR(150),
    T_ART_UNIDAD INT,
    T_ART_PRECIO DECIMAL(10, 2),
    T_ART_FECHA_CREA DATE,
    T_ART_FECHA_MOD DATE,
    CONSTRAINT FK_ART_TART FOREIGN KEY (T_TART_ID) REFERENCES TIPO_ART (T_TART_ID)
);

CREATE TABLE IF NOT EXISTS PRESUPUESTO (
    T_PRE_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    T_USU_ID INT,
    T_ART_ID INT,
    T_PRE_FECHA_CREA DATE,
    T_PRE_FECHA_MOD DATE,
    CONSTRAINT FK_PRE_USU FOREIGN KEY (T_USU_ID) REFERENCES USUARIO (T_USU_ID),
    CONSTRAINT FK_PRE_ART FOREIGN KEY (T_ART_ID) REFERENCES ART (T_ART_ID)
);